### PR TITLE
Time tracking and due date

### PR DESCRIPTION
**Pull request by MattMofDoom**
Hi @aliozgur,

This PR adds the ability to specify the Initial/Original Time Estimate and Remaining Time Estimate, as well as Due Date.

Each of these can be specified as a time expression (Xd Yh Zm, Xh Ym, etc). Due Date can also pass a specific date such as 2021-02-28.

All 3 can read properties from individual events which I expect to add to Seq.App.EventSchedule along with others, and if not matched, will use the 'static' property as a default.

This will allow for compatibility projects which require time tracking and/or due dates 😁

I made a test build on Seq.App.Atlassian.Jira2 as v0.2.11, which successfully tested fine. There is a test case added for time expression and date conversion. 

Cheers,

Matt

### CODE REVIEW

**Comment by MattMofDoom** [comment]
@aliozgur  FYI ... Event Schedule for Seq is now updated to use the new properties, along with the project key property 😁

It can create multiple log entries with properties that pass through to an instance of Seq.App.Atlassian.Jira that is monitoring a signal, which will then automatically create Jira issues for each log entry. It works really well.

Some info on addition of the new properties (along with the new 'multi-log token' templating) at https://mattmofdoom.com/event-schedule-v1018-schedule-multiple-log-entries-and-jira-related-enhancements/

Cheers,

Matt

**Review by aliozgur — COMMENTED** [review]
@MattMofDoom another great contribution! 👏👏👏
I have a minor suggestion. Can you modify the helptext of estimate properties and mention Seq.App.EventSchedule app along with a minimal informational text. Something like
> Consider installing Seq.App.EventSchedule app so that you can feed this property automatically from the event log stream.

**Comment by MattMofDoom** [comment]
@aliozgur worth a thought 😊 I think the more apps work together, all the better for the Seq ecosystem and community.

**Review by aliozgur — APPROVED** [review]

**Comment by aliozgur** [comment]
@MattMofDoom  v 0.2.10 uploaded to nuget. Thanks again for your contribution

**Pull request merged**
