### PR TITLE
Multiple enhancements - templating, tags to labels, issue priority, assignee, etc

### PR DESCRIPTION
**Pull request by MattMofDoom**
Hi @aliozgur ,

This pull request is a substantial enhancement to Seq.App.Atlassian.Jira.

This uplifts the app with a number of enhancements made to Seq.App.Opsgenie (some info/background at https://mattmofdoom.com/passing-priority-responder-and-tags-from-seq-to-opsgenie/).  In short, the enhancements include;

- Added Handlebar templating for Summary and Description fields. This allows substantial control over the formatting of a Jira issue - for example I have an instance configured with the following settings, which gives me a very nicely formatted Jira issue when drawing from events with  the Message and Description properties, per below screenshot;
  - Summary - {{Message}} 
  - Description - {{Description}}\n\n{{#each $Properties}}\*{{@key}}:\* {{this}}\n{{/each}}\n
- Ability to include tags from events as labels, drawn from an event property. These will append to any existing configured issue labels if they don't already exist.
- Ability to specify issue priority (as a static priority) 
- Ability to dynamically map issue priority from an event property (including @Level). Simply setting Priority Property to a property name (eg. Priority) and then specifying a Property Mapping (eg. Highest=Highest,High=High,Medium=Medium,Low=Low,Lowest=Low) will allow issues to be raised at an appropriate priority, with a default priority fallback.
- Optionally set an Assignee, either as a static value or drawn from an event property
- Added debug logging and exposed the error response from Jira to logging if a createissue is rejected
- Converted project to .NET SDK, added Nuget package details, added Nuget and application icons

I have a build of this on Nuget as Seq.App.Atlassian.Jira2 .. current build is 1.0.10. This allows me to test with Seq and Jira, and the enhancements work well 😁

image

Cheers,

Matt

### CODE REVIEW

**Review by aliozgur — COMMENTED** [review]
Deleted nuspec file (will update on master before publishing the update) and NuGet migration report html.

**Comment by aliozgur** [comment]
@MattMofDoom  thanks for your contribute. I've merged your changes locally and release version 0.2.5 on NuGet. I'll close the merge request. By the way, I've deleted couple of files in your PR by accident, you might want to delete your for and create an new one, sorry for that.

**Comment by MattMofDoom** [comment]
Thanks @aliozgur 😀

**Comment by MattMofDoom** [comment]
@aliozgur  Looks like the Nuget package is missing Handlebars.dll. Had to downgrade my install back to 0.2.4. 😢

image

**Comment by aliozgur** [comment]
@MattMofDoom  I'll look into this

**Comment by aliozgur** [comment]
@MattMofDoom  I think 0.2.7 fixes the problem. 

image

**Pull request closed without merging**
