### PR TITLE
Better Handlebars template interoperability with Jira text formatting notation

### PR DESCRIPTION
**Pull request by MattMofDoom**
Hi @aliozgur,

The main change in this pull request is that JiraDescription has been changed to a SettingInputType.LongText. This allows multi-line Handlebars templating within Seq, which then translates well within Jira.

For example if I set the JiraDescription in Seq to 

```
h1. Test

This is a test

||Test||Header|| 
|Test|{{Property}}|
||Test|{{Property2}}||

\*Test:\* {{Property3}}
```

Then I will get a well formatted Jira issue like:

image

This works really well with the Jira REST API! 😊

Other than this, I've done the following;

- The csproj settings resulted in nested "net47" folders being continually created. This is pretty weird behaviour, so I've modified this. 
- Updated Handlebars.net to v2.0.9
- Updated the csproj include statement for packaging to explicitly reference Handlebars.dll and SeqApps.Commons.dll. This should hopefully work with your Nuget packaging, while also avoiding the above nested net47 issue.

Cheers,

Matt

### CODE REVIEW

**Comment by MattMofDoom** [comment]
Hope you're well @aliozgur .. not sure if you've seen this pull but hoping to get it live soon 😊

**Comment by aliozgur** [comment]
@MattMofDoom thanks for your contribution! I've seen the PR and merge it soon.

**Comment by MattMofDoom** [comment]
Thanks @aliozgur .. will do checks over the weekend to make sure all is well 😁

**Comment by MattMofDoom** [comment]
@aliozgur  Tested and looks pretty good 😊

Blanked out a few details from the below screenshot, but you get the idea!

image

**Pull request merged**
